# Generated by Django 5.1.7 on 2025-03-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_home', models.FloatField()),
                ('distance_from_last_transaction', models.FloatField()),
                ('ratio_to_median_purchase_price', models.FloatField()),
                ('used_chip', models.BooleanField()),
                ('online_order', models.BooleanField()),
                ('is_fraud', models.BooleanField()),
                ('probability', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
